// <auto-generated />
namespace CondoSimples.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v102 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v102));
        
        string IMigrationMetadata.Id
        {
            get { return "201606280228269_v102"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
