// <auto-generated />
namespace CondoSimples.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Borrow8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Borrow8));
        
        string IMigrationMetadata.Id
        {
            get { return "201606230243160_Borrow8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
